<fieldset class="fieldset create account">
<div class="field github_url required">
    <label class="label" for="url_attribute">
        <span><?php echo __('Url Attribute');?></span>
    </label>
    <div class="control">
        <input type="url" name="github_url" id="url_attribute" 
               title="<?php echo __('Url Attribute'); ?>" class="input-text" data-validate="{required:true, 'validate-url':true}">
    </div>
</div>
</fieldset>